menu-name: "Visual Pathway Editor (Beta Version)"
page-name: "Visual Pathway Editor (Beta Version)"
is-beta: true
type: "model"
help-link: "https://github.com/geneontology/noctua-visual-pathway-editor/issues"
